ALTER TABLE COMMANDE
ADD CONSTRAINT FK_COM_CLI FOREIGN KEY(code_c)
REFERENCES CLIENT(code_c);

ALTER TABLE COMMANDE
ADD CONSTRAINT FK_COM_VEN FOREIGN KEY(code_v)
REFERENCES VENDEUR(code_v);

ALTER TABLE ligne_commande
ADD CONSTRAINT FK_LIG_COM FOREIGN KEY(numero) REFERENCES commande(numero),
ADD CONSTRAINT FK_LIG_PRO FOREIGN KEY (reference) REFERENCES produit(reference);